### ISSUE TITLE
Do we need these folders and files in the mulea package?

### ISSUE THREAD

**Issue by barizona** [ELTEbioinformatics/mulea#12]
- data
- dev
- inst/extdata
- man/figures
- src/.gitignore

It seems that these folders contain out-of-date files and/or file names.

If we need the inst/extdata can we use the files found in the description of the mulea github README?

@koralgooll

**Comment by stitam** [comment]
* data: As long as we use `data(geneSet)`, `data(selectDf)`, `data(poolDf)` within any of the examples we need the respective `.rda` files in the data directory. They are currently in use.
* inst/extdata: `model.gmt` is used within examples in `GenericFunctions.R` and also in the vignette, so it's needed. I couldn't find where the other files are used.
* man/figures: These were used in `README.md`. The paths were replaced in commit `a3a2cf918815a6f6c922c7b8fa2d1998c964da2e` (Quarto documentation from Eszter, @koralgooll, 2023-11-19). So it seems since 2023-11-19 these files are no longer needed.

**Comment by barizona** [comment]
thank you Tamás!
